package com.zplus.seckilldemo.DO;

import java.math.BigDecimal;

public class CommDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comm_id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private Integer commId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comm_name
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private String commName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comm_price
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private BigDecimal commPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comm_description
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private String commDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comm_sales
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private Integer commSales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commodity.comm_img_url
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private String commImgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comm_id
     *
     * @return the value of commodity.comm_id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public Integer getCommId() {
        return commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comm_id
     *
     * @param commId the value for commodity.comm_id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setCommId(Integer commId) {
        this.commId = commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comm_name
     *
     * @return the value of commodity.comm_name
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public String getCommName() {
        return commName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comm_name
     *
     * @param commName the value for commodity.comm_name
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setCommName(String commName) {
        this.commName = commName == null ? null : commName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comm_price
     *
     * @return the value of commodity.comm_price
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public BigDecimal getCommPrice() {
        return commPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comm_price
     *
     * @param commPrice the value for commodity.comm_price
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setCommPrice(BigDecimal commPrice) {
        this.commPrice = commPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comm_description
     *
     * @return the value of commodity.comm_description
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public String getCommDescription() {
        return commDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comm_description
     *
     * @param commDescription the value for commodity.comm_description
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setCommDescription(String commDescription) {
        this.commDescription = commDescription == null ? null : commDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comm_sales
     *
     * @return the value of commodity.comm_sales
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public Integer getCommSales() {
        return commSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comm_sales
     *
     * @param commSales the value for commodity.comm_sales
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setCommSales(Integer commSales) {
        this.commSales = commSales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commodity.comm_img_url
     *
     * @return the value of commodity.comm_img_url
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public String getCommImgUrl() {
        return commImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commodity.comm_img_url
     *
     * @param commImgUrl the value for commodity.comm_img_url
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setCommImgUrl(String commImgUrl) {
        this.commImgUrl = commImgUrl == null ? null : commImgUrl.trim();
    }
}