package com.zplus.seckilldemo.DO;

public class CommStockDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private Integer commStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comm_stock.comm_id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    private Integer commId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.id
     *
     * @return the value of comm_stock.id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.id
     *
     * @param id the value for comm_stock.id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.comm_stock
     *
     * @return the value of comm_stock.comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public Integer getCommStock() {
        return commStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.comm_stock
     *
     * @param commStock the value for comm_stock.comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setCommStock(Integer commStock) {
        this.commStock = commStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comm_stock.comm_id
     *
     * @return the value of comm_stock.comm_id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public Integer getCommId() {
        return commId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comm_stock.comm_id
     *
     * @param commId the value for comm_stock.comm_id
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    public void setCommId(Integer commId) {
        this.commId = commId;
    }
}