package com.zplus.seckilldemo.dao;

import com.zplus.seckilldemo.DO.CommStockDO;
import org.springframework.stereotype.Repository;

@Repository
public interface CommStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int insert(CommStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int insertSelective(CommStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    CommStockDO selectByPrimaryKey(Integer id);

    CommStockDO selectByCommId(Integer commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int updateByPrimaryKeySelective(CommStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comm_stock
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int updateByPrimaryKey(CommStockDO record);

    int decreaseStock(Integer commId,Integer quantityPurchased);
}