package com.zplus.seckilldemo.dao;

import com.zplus.seckilldemo.DO.PromoDO;
import com.zplus.seckilldemo.service.model.CommModel;
import org.springframework.stereotype.Repository;

@Repository
public interface PromoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int insert(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int insertSelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    PromoDO selectByPrimaryKey(Integer id);

    PromoDO selectByCommId(Integer commId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int updateByPrimaryKeySelective(PromoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promo_info
     *
     * @mbg.generated Fri Mar 15 14:17:34 CST 2019
     */
    int updateByPrimaryKey(PromoDO record);
}